SUBVOLUME="/"
FSTYPE="bcachefs"
ALLOW_USERS=""
ALLOW_GROUPS=""
SYNC_ACL="yes"
UNIQUE_NUMBERS="yes"
BACKGROUND_COMPARISON="no"
TIMELINE_CREATE="no"
TIMELINE_CLEANUP="no"
NUMBER_CLEANUP="no"
EMPTY_PRE_POST_CLEANUP="no"
